Repository graasp/graasp-app-text-analysis, pull requests merged in 2022-11, with the labels that each got.

#2 feat: create player view
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.2.4.cjs
  cypress/cypress.d.ts
  cypress/e2e/builder/enterSettings.cy.ts
  cypress/e2e/player/read/showApp.cy.js
  cypress/e2e/player/read/showApp.cy.ts
  cypress/fixtures/appSettings.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  package.json
  src/components/App.tsx
  src/components/common/display/Banner.tsx
  src/components/common/display/Highlighted.tsx
  src/components/common/display/TextDisplay.tsx
  src/components/common/settings/KeyWords.tsx
  src/components/common/settings/SaveButton.tsx
  src/components/common/settings/SetText.tsx
  src/components/views/admin/BuilderView.tsx
  src/components/views/read/PlayerView.tsx
  src/config/appSettingTypes.ts
  src/config/appSettings.ts
  src/config/selectors.ts
  src/config/stylingConstants.ts
  src/data/db.ts
  src/interfaces/window.d.ts
  yarn.lock
Labels: feature

#9 fix: add check for CI in hooks
  .husky/commit-msg
  .husky/post-checkout
  .husky/post-commit
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
Labels: bug

#4 fetch keywords definitions
  .eslintrc
  .github/workflows/cdelivery-s3-apps-caller.yml
  .github/workflows/cdeployement-s3-apps-caller.yml
  .github/workflows/cintegration-s3-apps-caller.yml
  .github/workflows/cypress.yml
  .github/workflows/update-staging-version.yml
  package.json
  src/components/App.tsx
  src/components/common/ChatbotWindow.tsx
  src/components/common/display/Banner.tsx
  src/components/common/display/Highlighted.tsx
  src/components/common/display/TextDisplay.tsx
  src/components/common/settings/SaveButton.tsx
  src/components/common/settings/SetText.tsx
  src/components/views/read/PlayerView.tsx
  src/config/appSettingTypes.ts
  src/config/appSettings.ts
  src/config/constants.ts
  src/config/stylingConstants.ts
  src/index.tsx
  yarn.lock
Labels: feature

#15 Save button feedback
  cypress/e2e/builder/enterSettings.cy.ts
  package.json
  src/components/common/ChatbotWindow.tsx
  src/components/common/display/TextDisplay.tsx
  src/components/common/settings/KeyWords.tsx
  src/components/common/settings/SaveButton.tsx
  src/components/common/settings/SetText.tsx
  src/components/views/read/PlayerView.tsx
  src/data/db.ts
  yarn.lock
Labels: feature

#20 17-addMarkdownToText
  package.json
  src/components/common/display/Highlighted.tsx
  yarn.lock
Labels: chore
